In [1]:
print("hi")
print("jupyter")

hi
jupyter


In [3]:
def is_balanced(s):
    if s:
        stack=[]
        pairs={
            ')':'(',
            ']':'[',
            '}':'{'
        }
        for ch in s:
            if ch in '([{':
                stack.append(ch)
            else:
                if not stack:
                    return False
                top=stack.pop()
                if top !=pairs[ch]:
                    return False  
        return len(stack)==0
    
print(is_balanced('{[(}]}'))    

False


In [11]:
import numpy as np

a=np.array([10,20,30,40])
print(a)
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(f"{a.ndim}->dimensions,{a.shape},{a.size},{a.dtype}")
print(f"{b.ndim}->dimensions,{b.shape},{b.size},{b.dtype}")


[10 20 30 40]
[[1 2 3]
 [4 5 6]]
1->dimensions,(4,),4,int64
2->dimensions,(2, 3),6,int64
